version: '2'

services:
  app:
    image: 10.100.198.200:5000/taskapi
    ports:
      - 8080
    environment:
      - SERVICE_NAME=taskapi
      - DB_HOST=taskapi.database

  app-blue:
    environment:
      - SERVICE_NAME=taskapi-blue
    extends:
      service: app
    depends_on:
      - db

  app-green:
    environment:
      - SERVICE_NAME=taskapi-green
    extends:
      service: app
    depends_on:
      - db

  db:
    container_name: taskapi.database
    image: mongo
    environment:
      - SERVICE_NAME=taskapi.database
