home: /data/jenkins
main_job_src: service-workflow-config.xml
service_redeploy_src: service-redeploy-config.xml

configs: [
  { src: "credentials.xml", dir: "/data/jenkins", file: "credentials.xml", mode: "0777" },
  { src: "cd-config.xml", dir: "/data/jenkins/nodes/cd", file: "config.xml", mode: "0777" },
  { src: "prod-config.xml", dir: "/data/jenkins/nodes/prod", file: "config.xml", mode: "0777" },
  { src: "swarm-master-config.xml", dir: "/data/jenkins/nodes/swarm-master", file: "config.xml", mode: "0777" },
  { src: "LogParserPublisher.xml", dir: "/data/jenkins", file: "hudson.plugins.logparser.LogParserPublisher.xml", mode: "0777" },
  { src: "parsing_rules", dir: "/data/jenkins", file: "parsing_rules", mode: "0777" },
  { src: "scriptApproval.xml", dir: "/data/jenkins", file: "scriptApproval.xml", mode: "0644" }
]

jobs: [
  {
    name: "taskapi-blue-green",
    service_name: "task-api",
    src: "taskapi-blue-green-config.xml"
  },
  {
    name: taskapi-main,
    service_name: "task-api",
    src: "taskapi-main-config.xml"
  },
  {
    name: taskapi-push,
    service_name: "task-api",
    src: "taskapi-push-config.xml"
  },
  {
    name: taskapi-pushSF,
    service_name: "task-api",
    src: "taskapi-pushSF-config.xml"
  }  
]

plugins:
  - git
  - log-parser
  - copyartifact
  - workflow-aggregator
  - workflow-multibranch
  - workflow-scm-step
  - docker-workflow
  - template-project
